# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'


- script: |
    git config --global user.email "you@there.com"
    git config --global user.name "pipeline wizard"
    npm version patch -m "version patch commit"
    cd ./projects/angular-odata
    npm version patch -m "version patch commit"
    cd ../../
    npm install --save-dev @angular-devkit/build-angular
    npm install -g @angular/cli@latest @angular/common @angular/platform-browser
    npm install --save-dev @angular/cli@latest 
    npm install
    ng build
    cd ./dist/angular-odata
    npm version patch -m "version patch commit"
  displayName: 'npm install and build'



- task: Npm@1
  inputs:
    command: 'publish'
    workingDir: './dist/angular-odata'
    publishRegistry: 'useFeed'
    publishFeed: '155346c4-4c3d-4269-a624-e98408645b68/37532069-a755-46e5-9614-9bd2c3da7795'

